# Generated by Django 5.0.6 on 2025-01-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('product_picture1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('product_picture2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('product_picture3', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_id', models.CharField(max_length=255, unique=True)),
                ('gold_category', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('carat', models.PositiveIntegerField(choices=[(22, '22K'), (20, '20K'), (18, '18K'), (14, '14K')])),
                ('labour_percentage', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('diamond_weight_in_gold', models.FloatField(blank=True, null=True)),
                ('gold_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bangle_size', models.CharField(blank=True, max_length=10, null=True)),
                ('ring_bracelet_size', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_details', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_id', models.CharField(max_length=255, unique=True)),
                ('diamond_shape', models.CharField(max_length=50)),
                ('diamond_type', models.CharField(choices=[('natural', 'Natural'), ('lab_grown', 'Lab Grown')], max_length=50)),
                ('diamond_color', models.CharField(max_length=50)),
                ('diamond_carat', models.FloatField()),
                ('diamond_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_details', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Silver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_id', models.CharField(max_length=255, unique=True)),
                ('silver_category', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('silver_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bangle_size', models.CharField(blank=True, max_length=10, null=True)),
                ('ring_bracelet_size', models.CharField(blank=True, max_length=10, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver_details', to='main.product')),
            ],
        ),
    ]
