# Generated by Django 5.0.6 on 2025-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gold_carat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=1),
        ),
    ]
