# Generated by Django 5.0.6 on 2025-01-28 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('gold_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('silver_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
