# Generated by Django 5.0.6 on 2025-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_metalrate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalrate',
            name='time',
            field=models.TimeField(),
        ),
    ]
