# Generated by Django 5.0.6 on 2025-01-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_metalrate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond',
            name='product_name',
        ),
    ]
