# Generated by Django 5.0.6 on 2025-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_diamond_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='silver',
            name='diamond_weight_in_silver',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
