# Generated by Django 5.0.6 on 2025-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_gold_diamond_weight_in_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='diamond_quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold',
            name='gold_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silver',
            name='silver_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
