# Generated by Django 5.0.6 on 2025-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_diamond_diamond_quantity_gold_gold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture1',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture2',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture3',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
