# Generated by Django 5.0.6 on 2025-01-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_product_picture1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_picture1',
            new_name='image',
        ),
    ]
