# Generated by Django 5.0.6 on 2025-01-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_product_picture1_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_picture1',
        ),
    ]
