# Generated by Django 5.1.3 on 2025-02-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
    ]
