# Generated by Django 5.0.6 on 2025-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='tax',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold',
            name='diamond_rate_in_gold',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gold',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='tax',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silver',
            name='diamond_rate_in_silver',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silver',
            name='tax',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
