# Generated by Django 5.0.6 on 2025-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_diamond_tax_gold_diamond_rate_in_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='diamond_rate_in_gold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gold',
            name='other_charges',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='silver',
            name='diamond_rate_in_silver',
            field=models.PositiveIntegerField(),
        ),
    ]
